ci(root): fix auto-approve in build workflow
Error: Resource not accessible by integration. In some cases, the GitHub
token used for actions triggered from `pull_request` events are
read-only, which can cause this problem. Switching to the
`pull_request_target` event typically resolves this issue.